### PR TITLE
Daily dev

### PR DESCRIPTION
**Pull request by konchokdolma**

### CODE REVIEW

**Comment by mikkokotila** [comment]
Hello :) I checked out the callback function, but it does not seem to give us the kind of flexibility we need to have. 

I was thinking something like this (note it has two different callbacks): 

from keras.callbacks import EarlyStopping
from keras.callbacks import ReduceLROnPlateau
```

def callback_earlystop(monitor='loss', min_delta=0.1, patience=10, verbose=1, mode='auto'):
    
    '''Callback Function for EarlyStopping
    
    WHAT: Creates the parameters for early stopping of the training process.
    
    '''
    
    callback = [EarlyStopping(monitor=monitor,
                                              min_delta=min_delta,
                                              patience=patience,
                                              verbose=verbose,
                                              mode=mode)]
    
    return callback


def callback_droplearning(monitor='val_loss',
                          factor=0.1,
                          patience=10,
                          verbose=0,
                          mode='auto',
                          epsilon=0.0001,
                          cooldown=0, 
                          min_lr=0):

    callback = [ReduceLROnPlateau(monitor=monitor,
                                 factor=factor,
                                 patience=patience,
                                 verbose=verbose,
                                 mode=mode,
                                 epsilon=epsilon,
                                 cooldown=cooldown, 
                                 min_lr=min_lr)]
    
    return callback
```
What do you think?

**Comment by mikkokotila** [comment]
Or did I miss something?

**Comment by konchokdolma** [comment]
yes, changed)

**Comment by mikkokotila** [comment]
Great work!  But as we discussed, please see the code example I'm providing above for call backs...you could create an issue related with the "two different patience" aspect, or then maybe it's easier to just first do the earlystop well because that's what we need for hyperscan pretty urgently.  Once we do that well, then it's easier to see about the others.

**Pull request merged**
